import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { getClientDealUrl, getCreatorDealUrl, generateDealCode } from '../lib/deal-url';
import { getCanonicalDeliverables } from '../lib/deals/canonical-deliverables';
import { buildDealCardData } from '../lib/deal-card-data';
import {
  isValidContractStatusTransition,
  serializeContract,
  serializeContractVersion,
} from '../lib/contracts/state';
import type { Deal, Milestone, Deliverable, FileVersion } from '../lib/types';

describe('DELT — Complete End-to-End Deal Lifecycle Audit', () => {

  describe('1. Stage 1: Deal Creation & Handoff', () => {
    test('Canonical client URL generated by deal_code contains no preview parameters or tokens', () => {
      const dealCode = generateDealCode();
      const clientUrl = getClientDealUrl(dealCode, 'shreyan');

      assert.ok(clientUrl.includes(`/shreyan/${encodeURIComponent(dealCode)}`));
      assert.equal(clientUrl.includes('preview='), false);
      assert.equal(clientUrl.includes('previewMode='), false);
      assert.equal(clientUrl.includes('role=creator'), false);
    });

    test('Creator deal URL points to creator route /deals/{deal_code}', () => {
      const dealCode = 'DLT-TEST999';
      const creatorUrl = getCreatorDealUrl(dealCode);

      assert.ok(creatorUrl.includes('/deals/DLT-TEST999'));
    });
  });

  describe('2. Stage 2: Client OTP & Session Authorization Security', () => {
    test('requireClientDealAccess rejects requests without active session cookie or matching auth', () => {
      const fs = require('fs');
      const path = require('path');
      const dealAuthContent = fs.readFileSync(
        path.join(process.cwd(), 'lib', 'deal-auth.ts'),
        'utf-8'
      );

      assert.ok(
        dealAuthContent.includes('delt_client_session_${deal.id}'),
        'Session cookie must be deal-scoped'
      );
      assert.equal(
        dealAuthContent.includes('isCreator: true'),
        false,
        'requireClientDealAccess must never fall back to isCreator'
      );
    });

    test('Creators cannot perform client-only actions (message send as client)', () => {
      const fs = require('fs');
      const path = require('path');
      const sendRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'messages', 'send', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        sendRoute.includes('Creators cannot send messages as client.'),
        'Message route must block creators from sending messages as client'
      );
    });

    test('Creators cannot initiate client-side payments', () => {
      const fs = require('fs');
      const path = require('path');
      const createOrderRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'payments', 'create-order', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        createOrderRoute.includes('Creators cannot make payments.'),
        'Payment create-order route must block creators from creating payment orders'
      );
    });
  });

  describe('3. Stage 3: Scope, Deliverables & Milestones Consistency', () => {
    test('Operational deals.scope is primary source for canonical deliverables', () => {
      const deal: Partial<Deal> = {
        id: 'deal-lifecycle-1',
        scope: ['Brand Identity', 'Mobile App UI', 'Design System'],
        paymentStatus: 'pending',
        status: 'in_progress',
        createdAt: '2026-01-01T00:00:00Z',
      };

      const canonical = getCanonicalDeliverables(deal as Deal, [], []);
      assert.equal(canonical.length, 3);
      assert.equal(canonical[0].name, 'Brand Identity');
      assert.equal(canonical[1].name, 'Mobile App UI');
      assert.equal(canonical[2].name, 'Design System');
    });

    test('Milestone progress is accurately calculated as completed / total count', () => {
      const milestones: Array<Pick<Milestone, 'status'>> = [
        { status: 'completed' },
        { status: 'in_progress' },
        { status: 'pending' },
        { status: 'completed' },
      ];

      const cardData = buildDealCardData({
        deal: { title: 'Lifecycle Deal', dealCode: 'DLT-LIFE1' } as any,
        milestones,
      });

      assert.equal(cardData.totalMilestones, 4);
      assert.equal(cardData.completedMilestones, 2);
      assert.equal(cardData.progressPercent, 50);
    });
  });

  describe('4. Stage 4: Agreement / Contract Lifecycle & Snapshot Isolation', () => {
    test('Contract status transitions follow strictly valid lifecycle', () => {
      assert.ok(isValidContractStatusTransition('draft', 'sent'));
      assert.ok(isValidContractStatusTransition('sent', 'viewed'));
      assert.ok(isValidContractStatusTransition('viewed', 'accepted'));
      assert.ok(isValidContractStatusTransition('sent', 'accepted'));
      assert.equal(isValidContractStatusTransition('accepted', 'draft'), false);
    });

    test('Stale version acceptance is rejected', () => {
      const fs = require('fs');
      const path = require('path');
      const acceptRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'deals', '[code]', 'contract', 'accept', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        acceptRoute.includes('Cannot accept an outdated agreement version'),
        'Contract accept route must reject stale version IDs'
      );
    });

    test('Contract acceptance is idempotent when already accepted', () => {
      const fs = require('fs');
      const path = require('path');
      const acceptRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'deals', '[code]', 'contract', 'accept', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        acceptRoute.includes('idempotent: true'),
        'Contract accept route must return idempotent response if already accepted'
      );
    });
  });

  describe('5. Stage 5: Work Delivery & Deliverables Review State Machine', () => {
    test('Deliverable review route requires requireClientDealAccess', () => {
      const fs = require('fs');
      const path = require('path');
      const approveRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'deliverables', 'approve', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        approveRoute.includes('requireClientDealAccess'),
        'Deliverables approve route must enforce client deal authorization'
      );
    });

    test('Only pending_review version can be reviewed/approved', () => {
      const fs = require('fs');
      const path = require('path');
      const approveRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'deliverables', 'approve', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        approveRoute.includes("latestVersion.status !== 'pending_review'"),
        'Deliverable review route must verify status is pending_review'
      );
    });
  });

  describe('6. Stage 6: Invoice & Payment Integrity', () => {
    test('Client-view invoice endpoint enforces requireClientDealAccess and hides drafts', () => {
      const fs = require('fs');
      const path = require('path');
      const invoiceRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'invoices', '[id]', 'client-view', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        invoiceRoute.includes('requireClientDealAccess(request, invoice.deal_id)'),
        'Invoice client-view must verify client access for matching deal_id'
      );
      assert.ok(
        invoiceRoute.includes("invoice.status === 'draft'"),
        'Invoice client-view must hide draft invoices from client'
      );
    });

    test('Payment verification checks Razorpay signature and uses atomic update', () => {
      const fs = require('fs');
      const path = require('path');
      const verifyRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'payments', 'verify', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        verifyRoute.includes('verifyRazorpaySignature'),
        'Payment verify route must verify signature'
      );
      assert.ok(
        verifyRoute.includes(".eq('state', 'pending')"),
        'Payment verify route must atomically update pending payments'
      );
    });

    test('finalizeDealPayment idempotency check prevents double-finalization', () => {
      const fs = require('fs');
      const path = require('path');
      const completionContent = fs.readFileSync(
        path.join(process.cwd(), 'lib', 'deals', 'completion.ts'),
        'utf-8'
      );

      assert.ok(
        completionContent.includes("deal.payment_status === 'paid' || deal.status === 'completed'"),
        'finalizeDealPayment must exit immediately if deal is already paid or completed'
      );
    });
  });

  describe('7. Stage 7: Deal Closure & Retention', () => {
    test('Deal close route requires creator access and updates file retention', () => {
      const fs = require('fs');
      const path = require('path');
      const closeRoute = fs.readFileSync(
        path.join(process.cwd(), 'app', 'api', 'deals', '[code]', 'close', 'route.ts'),
        'utf-8'
      );

      assert.ok(
        closeRoute.includes('requireCreatorDealAccess'),
        'Close deal route must require creator authorization'
      );
      assert.ok(
        closeRoute.includes("deletionStatus: 'retention'"),
        'Close deal route must place file versions into retention'
      );
    });
  });

});
